const HairStyle = {
  ShortMessy: {
    id: 1,
    name: 'Short Messy',
    model: '/models/hair/01_ShortMessy.glb',
    position: [0, -150, -2],
    scale: [110, 100, 110],
    thumbnail: '/images/hair/01_ShortMessy.png',
  },
  LayeredBob: {
    id: 2,
    name: 'Layered Bob',
    model: '/models/hair/02_LayeredBob.glb',
    position: [0, -151, -0.5],
    scale: [105, 100, 110],
    thumbnail: '/images/placeholder.png',
  },

  /*
  ClassicShort: {
    id: 3,
    name: 'Classic Short',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  SideSweep: {
    id: 4,
    name: 'Side Sweep',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  StraightBob: {
    id: 5,
    name: 'Straight Bob',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  ShortBangs: {
    id: 6,
    name: 'Short Bangs',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  LowPonytail: {
    id: 7,
    name: 'Low Ponytail',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  WavyBob: {
    id: 8,
    name: 'Wavy Bob',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  SpikyShort: {
    id: 9,
    name: 'Spiky Short',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  GirlBraids: {
    id: 10,
    name: 'Girl Braids',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  TwinBuns: {
    id: 11,
    name: 'Twin Buns',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  StraightTwinTails: {
    id: 12,
    name: 'Straight Twin Tails',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  Pigtails: {
    id: 13,
    name: 'Pigtails',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  FluffyShort: {
    id: 14,
    name: 'Fluffy Short',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  LayeredMedium: {
    id: 15,
    name: 'Layered Medium',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  ShaggyShort: {
    id: 16,
    name: 'Shaggy Short',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  LongWavy: {
    id: 17,
    name: 'Long Wavy',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  TousledMedium: {
    id: 18,
    name: 'Tousled Medium',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  SidePonytail: {
    id: 19,
    name: 'Side Ponytail',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  LayeredLong: {
    id: 20,
    name: 'Layered Long',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  StraightLong: {
    id: 21,
    name: 'Straight Long',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  ShortBowl: {
    id: 22,
    name: 'Short Bowl',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  CurlyShort: {
    id: 23,
    name: 'Curly Short',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  BobWithBangs: {
    id: 24,
    name: 'Bob With Bangs',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  BraidedBun: {
    id: 25,
    name: 'Braided Bun',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  ShortCurly: {
    id: 26,
    name: 'Short Curly',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  WavyTwinTails: {
    id: 27,
    name: 'Wavy Twin Tails',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  ShortSpiky: {
    id: 28,
    name: 'Short Spiky',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  ShortLayered: {
    id: 29,
    name: 'Short Layered',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  FluffyBob: {
    id: 30,
    name: 'Fluffy Bob',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },
  ShortAfro: {
    id: 31,
    name: 'Short Afro',
    model: null,
    position: [0, 0, 0],
    scale: [1, 1, 1],
    thumbnail: '/images/placeholder.png',
  },

  */
};

export default HairStyle;